### ISSUE TITLE
Do you know how to make a monitor receive volume/turn on controls?

### ISSUE THREAD

**Issue by JonathanJumper** [RoggerTan/Android-TV-Controller-Server#1]
It is not working on my tivo stream

**Comment by RoggerTan** [comment]
Hi @JonathanJumper, very sorry for the late reply. 
This server is for controlling Android TV devices while making no interactions with others such as monitor or TV screen. In other words, only Android system volume can be directly modified. 
However, if TiVo Stream has a specific keycode which can control the monitor, you can bruteforcing to figure out: 

```
http://<server endpoint>/signal?key=<keycode>
```

Try replacing `<keycode>` by any number. Let's start with those defined in [key_codes.py](https://github.com/RoggerTan/Android-TV-Controller-Server/blob/master/key_codes.py) first. 

I hope it helps!
